filebeat.inputs:
- type: log
  enabled: true
  paths:
     - /path/to/sml/Backend/backend/crud/user_crud/logs/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
